name: Flutter Tests

on:
  push:
    branches:
      - master  # Set the branch to trigger the workflow (e.g., main, master)

jobs:
  test:
    runs-on: macos-latest  # Use macOS runner for Flutter testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout the repository code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'  # Specify the Flutter version (e.g., 2.10.3)

      - name: Navigate to Flutter project directory
        run: cd frontend/crop_final_app  # Change directory to your Flutter project

      - name: Install dependencies
        run: flutter pub get  # Install Flutter dependencies

      - name: Run Flutter tests
        run: flutter test  # Run Flutter tests located in the test directory
