name: Print Message

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, CI/CD! This is a test message."
