name: Flutter Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3' # Update with your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter app
        run: flutter build apk --release
